const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
    SESSION_ID: process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRVBNb2FqSHpCNnVXVUUraU5IRllrbm9yMzkzRHFGcUlNYnhhbFZ2bHJtcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMDk2WGhadzFKQWhjQkNEckN4ZzhwcU9VdWNnTGczL3dGR1hPZi9iZHdqUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0Q2ozN1NCVHV4dTBZZTN2WDByamxNdUZ4dStBWTlxWWVVaE9SdDdEMTM0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJMSnZ2Z3ZPSHpKV0Q5ZGlxMUxQTmN1b2NvOVBwa2cvMnVNYVVIQlBZakNBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVKS1lWME5NNzhUTExiYWEvYUFCS3NUbEhQNXNXN29kenF3T2plbzRFV2c9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikg5bWJOYzZzQi84V3RzSkVpYm5pcEhKNHhFWnNVeC91ejdBSXpMZFd4d0E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYURYcmhoaktVVUJDdDl0Ry9vZi8zSDlWZVVsVEZRdVFEd0pUOTB4YnQyWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaGkvZ1lQY2hEelhxZVBtOVpRdWdlRmV6K3RaTE9iY21ucXViOFdDWnZtTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldTbk4rZmZDcktxaTVBQk9RWWVmT1lnY2VqSE1yRCtKbVdZc3VXWTNXZWZtQWY4cUpFcmt2K09DaitNTUl1dk5sOU1XL1lST1ZDM0Y5K3BBVFM1emlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTgsImFkdlNlY3JldEtleSI6IlAzS01oTklqR0UvWnloeVQ3NmRMYnJKRkFmMFZydlRNRytJVXNhWEJ4T1k9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjc2ODM0MjU5NDNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQkUyREY4NjhEQkYzNjQxRUU4MDVDQzZGNTc5Mjk1NEMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTcyNTQ2NX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjc2ODM0MjU5NDNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNkZDRDhGRkMwNTU1ODRBMzEzNUQ1QkNGM0YzQ0U2QTcifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTcyNTQ2NX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjc2ODM0MjU5NDNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMDE3NEU2QURGRENCM0ZGQ0VDNDZDOUJCRTg3Q0EzOEUifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTcyNTQ2N30seyJrZXkiOnsicmVtb3RlSmlkIjoiMjc2ODM0MjU5NDNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiODAyRUY5MDU2MDczMzRGNEM1MzNDMzA2MjU5REExRUMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTcyNTQ2OH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiR1dna204OWpTeGF1UUI2QkQ5bWFzQSIsInBob25lSWQiOiI3NmFkNGFhYy02ZDM5LTRkZGQtOGI4ZS00NDNjODg3OWFlZjAiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiak5pWm5DNXJZTHl1d0srbkRlU0UvQmZTRTBnPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVPbHRwak1DQllxR0psVzRaZ3RaYjdWK09SOD0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJWVFk2UlBLUiIsIm1lIjp7ImlkIjoiMjc2ODM0MjU5NDM6MUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJTZWRp8J+XvyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTUdiaVlRR0VJcWoxTHNHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiL2lBNjZHbjFKU1d2cDJRMm5yNEJWOGMrT0VFbFhwblB3ZXFjRFF6bDN4QT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiUlAvRnpSRUhOb1NqZHNTRkp4ZVVOMmVxQTBEVEUvazUxUHdBSzNNZVhRd2k2WU1QL0N3bGpOVTRyWGxraGc1M3ZvQWVxazZsSGI2TDRFVWdxRzc2QlE9PSIsImRldmljZVNpZ25hdHVyZSI6InZOeTU3NXBRaWlvMnNmNVZXK0VtMnlVcFhuUW9FVy9RQWp2Sm50cEs1L3pYSFNDRGkzdVAvZGZuN01nL1RLUGdHbFRnWkRVZkZjT2gyWTBscHFacmlnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjc2ODM0MjU5NDM6MUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJmNGdPdWhwOVNVbHI2ZGtOcDYrQVZmSFBqaEJKVjZaejhIcW5BME01ZDhRIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM1NzI1NDYzLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQURWRyJ9",
    CAPTION: process.env.CAPTION || "*ᴘᴏᴡᴅᴇʀᴇᴅ ʙʏ ᴀɴsᴀʀ-ᴘᴀɴʜᴡᴀʀ*",
    ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
    READ_MESSAGE: process.env.READ_MESSAGE || "false", // Added auto-read configuration
    AUTO_TYPING: process.env.AUTO_TYPING || "true",
    CURRENT_STATUS: process.env.CURRENT_STATUS || "false",
    MODE: process.env.MODE || "public",
    AUTO_VOICE: process.env.AUTO_VOICE || "false",
    AUTO_STICKER: process.env.AUTO_STICKER || "false",
    AUTO_REPLY: process.env.AUTO_REPLY || "false",
    ALIVE_IMG: process.env.ALIVE_IMG || "https://i.ibb.co/MNpy6DM/Manul-Ofc-X.jpg",
    ALIVE_MSG: process.env.ALIVE_MSG || "HII DEAR IM ONLINE I'M PANHWAR-MD WHATSAPP BOT 😊♻️",
    ANTI_LINK: process.env.ANTI_LINK || "true",
    ANTI_BAD: process.env.ANTI_BAD || "true",
    PREFIX: process.env.PREFIX || ".",
    FAKE_RECORDING: process.env.FAKE_RECORDING || "false",
    AUTO_REACT: process.env.AUTO_REACT || "true",
    HEART_REACT: process.env.HEART_REACT || "false",
    OWNER_REACT: process.env.OWNER_REACT || "false",
    BOT_NAME: process.env.BOT_NAME || "ᴀᴡᴀɪs ᴍᴅ",
    AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY || "true",
    AUTO_STATUS__MSG: process.env.AUTO_STATUS__MSG || "`𝒚𝒐𝒖𝒓 𝒔𝒕𝒂𝒕𝒖𝒔 𝒔𝒆𝒆𝒏 𝒋𝒖𝒔𝒕 𝒏𝒐𝒘 𝒃𝒚 𝒑𝒂𝒏𝒉𝒘𝒂𝒓 𝒎𝒅`",
    OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};
